# Generated by Django 4.2.11 on 2024-05-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_signup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
