# Generated by Django 4.2.11 on 2024-05-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_signup_gender_remove_signup_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
