# Generated by Django 4.2.11 on 2024-05-10 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_signup_gender_signup_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.FileField(upload_to='screenshot/')),
                ('back', models.FileField(upload_to='screenshot/')),
                ('left', models.FileField(upload_to='screenshot/')),
                ('right', models.FileField(upload_to='screenshot/')),
                ('color_code', models.CharField(max_length=255, null=True)),
                ('text_font', models.CharField(max_length=255, null=True)),
                ('product_price', models.IntegerField()),
                ('size', models.CharField(max_length=255, null=True)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.signup')),
            ],
        ),
    ]
