# Generated by Django 4.2.11 on 2024-05-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
