# Generated by Django 4.2.11 on 2024-05-13 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_carts_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='back',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='front',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='left',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='right',
        ),
        migrations.AddField(
            model_name='carts',
            name='front_image',
            field=models.FileField(blank=True, null=True, upload_to='screenshot/'),
        ),
        migrations.AddField(
            model_name='carts',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='design_images/')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='userapp.carts')),
            ],
        ),
    ]
