# Generated by Django 4.2.11 on 2024-05-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_carts_back_remove_carts_front_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='cart',
        ),
        migrations.AddField(
            model_name='carts',
            name='images',
            field=models.ManyToManyField(related_name='designs', to='userapp.design'),
        ),
    ]
