# Generated by Django 4.2.11 on 2024-05-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_remove_carts_images_design_carts_alter_design_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
