# Generated by Django 4.2.11 on 2024-05-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_remove_order_order_order_cart_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='orderID',
        ),
    ]
