# Generated by Django 4.2.11 on 2024-05-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_rename_order_id_order_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
