# Generated by Django 4.2.11 on 2024-05-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_remove_carts_order_id_carts_orderid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
