# Generated by Django 4.2.11 on 2024-05-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_remove_modelimage_image_modelimage_glb_file'),
        ('userapp', '0022_orderitems_ordersatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='text_font',
        ),
        migrations.AddField(
            model_name='carts',
            name='colorCode_textFont',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carts',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.product'),
        ),
    ]
