# Generated by Django 4.2.11 on 2024-05-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_remove_carts_color_code_remove_carts_text_font_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='colorCode_textFont',
            new_name='color_code',
        ),
        migrations.AddField(
            model_name='carts',
            name='text_font',
            field=models.TextField(blank=True, null=True),
        ),
    ]
