# Generated by Django 4.2.11 on 2024-05-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_rename_colorcode_textfont_carts_color_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='productID',
            new_name='pid',
        ),
    ]
