# Generated by Django 4.2.11 on 2024-05-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_universities_faqs_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_faqs', to='menu.categories'),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_size', to='menu.categories'),
        ),
    ]
