# Generated by Django 4.2.11 on 2024-05-07 05:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_faqs_category_alter_size_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('priority',)},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_list_image', models.ImageField(upload_to='list_image/')),
                ('product_details_image', models.ImageField(upload_to='details_image/')),
                ('description', ckeditor.fields.RichTextField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Deactive')], default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_product', to='menu.categories')),
            ],
        ),
    ]
