# Generated by Django 4.2.11 on 2024-05-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_product_priority_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_details_image',
            field=models.FileField(upload_to='details_image/'),
        ),
    ]
