# Generated by Django 4.2.11 on 2024-05-09 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_product_product_details_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_details_image',
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='button_image/')),
                ('full_image', models.ImageField(upload_to='full_image/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_model_image', to='menu.categories')),
            ],
        ),
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('button_image', models.ImageField(upload_to='button_image/')),
                ('full_image', models.ImageField(upload_to='full_image/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_design_image', to='menu.categories')),
            ],
        ),
    ]
