# Generated by Django 4.2.11 on 2024-05-09 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_remove_product_product_details_image_modelimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_design_image', to='menu.product'),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_model_image', to='menu.product'),
        ),
    ]
