# Generated by Django 4.2.11 on 2024-05-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_designimage_product_alter_modelimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelimage',
            name='full_image',
        ),
    ]
