# Generated by Django 4.2.11 on 2024-05-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_remove_modelimage_full_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='designimage',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Deactive')], default=1),
        ),
        migrations.AddField(
            model_name='modelimage',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Deactive')], default=1),
        ),
    ]
