# Generated by Django 4.2.11 on 2024-05-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_designimage_status_modelimage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelimage',
            name='image',
        ),
        migrations.AddField(
            model_name='modelimage',
            name='glb_file',
            field=models.FileField(null=True, upload_to='glb_file/'),
        ),
    ]
